FROM ${DOCKERFILE_VERSION}

RUN apt-get update && \
    apt-get install -y \
      default-libmysqlclient-dev \
      build-essential \
      wait-for-it \
      python${ADDITIONAL_PYTHON_VERSION} python${ADDITIONAL_PYTHON_VERSION}-distutils python${ADDITIONAL_PYTHON_VERSION}-dev

RUN pip install tox

WORKDIR /home/app

COPY djangocms_time_wizard/ /home/app/djangocms_time_wizard/
COPY tests/ /home/app/tests/
COPY setup.py /home/app/setup.py
COPY tox.ini /home/app/tox.ini
COPY README.rst /home/app/README.rst
COPY .coveragerc /home/app/.coveragerc
