# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-12 09:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('time_wizard', '0003_auto_20190706_0833'),
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWizardModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='djangocms_time_wizard_timewizardmodel',
                    serialize=False,
                    to='cms.CMSPlugin')),
                ('time_wizard', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='time_wizard.TimeWizardModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
